apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-old-events
  namespace: kube-system
spec:
  schedule: "0 */8 * * *"   # chạy mỗi 8 tiếng
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cleanup-events-sa
          restartPolicy: OnFailure
          containers:
            - name: cleanup
              image: bitnami/kubectl:latest
              command:
                - /bin/bash
                - -c
                - |
                  echo "Cleaning up old events older than 8 hours..."
                  kubectl get events --all-namespaces -o json \
                  | jq -r '
                      .items[]
                      | select(.lastTimestamp < (now - 8*60*60 | strftime("%Y-%m-%dT%H:%M:%SZ")))
                      | "kubectl delete event \(.metadata.name) -n \(.metadata.namespace)"
                    ' \
                  | bash
