apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup-events-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleanup-events-role
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cleanup-events-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cleanup-events-role
subjects:
  - kind: ServiceAccount
    name: cleanup-events-sa
    namespace: kube-system
